### ISSUE TITLE
washing won't start

### ISSUE THREAD

**Issue by KenanDK666** [Manliketjb/moneywash#1]
im having an issue with the washing to start, im getting this error in the console.

SCRIPT ERROR: citizen:/scripting/lua/scheduler.lua:881: No such export Start in resource rprogress

**Comment by Manliketjb** [comment]
> im having an issue with the washing to start, im getting this error in the console.
> 
> SCRIPT ERROR: citizen:/scripting/lua/scheduler.lua:881: No such export Start in resource rprogress

you don't have rprogress

**Comment by Manliketjb** [comment]
or the script is starting before rprogress

**Comment by KenanDK666** [comment]
it was an unpacking issue since i didnt notice rprogress was in double folders

**Comment by Manliketjb** [comment]
> it was an unpacking issue since i didnt notice rprogress was in double folders

no worries, all good now?
